[window]
# Background transparency
opacity = 0.8

# Window padding
padding = { x = 10, y = 10 }

# Centering
dynamic_padding = true

# Font configurations
[font]
normal = { family = "monospace", style = "Regular" }
bold = { family = "monospace", style = "Bold" }
italic = { family = "monospace", style = "Italic" }
bold_italic = { family = "monospace", style = "Bold Italic" }
size = 13.5

# $TERM correction
[env]
TERM = "xterm-256color"
FZF_DEFAULT_OPTS = "--color=bg:,bg+:#3c3836,fg:#d4be98,fg+:#d4be98,hl:#a9b665,hl+:#a9b665,info:#7daea3,prompt:#d3869b,pointer:#a9b665,marker:#ea6962,spinner:#d8a657,header:#89b482,border:#3c3836"

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#1d2021'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#4d5051'
red     = '#ff847b'
green   = '#d3e17e'
yellow  = '#ffcf6d'
blue    = '#9cd9cc'
magenta = '#ffacc2'
cyan    = '#acdfff'
white   = '#fff0be'
