[window]
# Background transparency
opacity = 0.8

# Window padding
padding = { x = 10, y = 10 }

# Centering
dynamic_padding = true

# Font configurations
[font]
normal = { family = "monospace", style = "Regular" }
bold = { family = "monospace", style = "Bold" }
italic = { family = "monospace", style = "Italic" }
bold_italic = { family = "monospace", style = "Bold Italic" }
size = 13.5

# $TERM correction
[env]
TERM = "xterm-256color"

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#1d2021'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#454849'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
